version: "3"

services:
  redis:
    image: registry.gitlab.com/qio/standard/redis:latest
    ports:
      - 6379:6379

  api:
    build: ./api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  nginx:
    image: registry.gitlab.com/qio/standard/nginx:1.21-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf